apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifacts-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/artifacts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfp-artifacts-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: artifacts-pv
  storageClassName: ""
